name: list-versions
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: aquaproj/aqua-installer@e6160e5a751bbcbd337a834eb75c15ba9ca206ae # v3.0.2
        with:
          aqua_version: v2.30.0

      - run: aws --region us-east-1 elasticache describe-cache-engine-versions --engine memcached | jq -r ".CacheEngineVersions[].EngineVersion" | uniq > versions.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: suzuki-shunsuke/github-actions-renovate-github-tags-data-source@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
